name: Flutter Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Directory Structure
        run: ls -R

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: true

      - name: Navigate to frontend directory
        run: |
          cd frontend
          echo "Current directory: $(pwd)"
          ls -la

      - name: Install dependencies
        working-directory: ./frontend
        run: flutter pub get

      - name: Run tests
        working-directory: ./frontend
        run: flutter test || true  

      - name: Build APK
        working-directory: ./frontend
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ./frontend/build/app/outputs/flutter-apk/app-release.apk

      - name: Build App Bundle
        working-directory: ./frontend
        run: flutter build appbundle --release
      
      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle-release
          path: ./frontend/build/app/outputs/bundle/release/app-release.aab
